In [1]:
from a01_clean_data import clean_data
from b02_fetch_weather import fetch_weather, clean_weather_data
import pandas as pd
import matplotlib as mpl
import openmeteo_requests
import requests_cache
from retry_requests import retry
import holidays
ca_holidays = holidays.US(subdiv='CA', years=[2024, 2025, 2026])

dfgym, mindate, maxdate = clean_data('../data/raw/data.csv')
dfweather = fetch_weather(mindate, maxdate)
dfweather = clean_weather_data(dfweather)
dfweather.to_csv("../data/processed/clean_weather_data.csv", index=False) # Export as a csv

In [2]:
# Merge dataframes
df = pd.merge(dfgym, dfweather, on=["key_date", "hour"], how="left")

In [3]:
# Reorder columns
df = df[["key_date","year","month","day","hour","minute","number_people","day_of_week","is_weekend","is_holiday","is_start_of_semester","is_during_semester","temp_f","rain_mm","encoded_weather_code","weather_type"]]
df[df["day_of_week"] == "Friday"]

,key_date,year,month,day,hour,minute,number_people,day_of_week,is_weekend,is_holiday,is_start_of_semester,is_during_semester,temp_f,rain_mm,encoded_weather_code,weather_type
0,2015-08-14,2015,8,14,17,0,37,Friday,False,False,False,False,80.6576,0.0,0,Clear sky
1,2015-08-14,2015,8,14,17,20,45,Friday,False,False,False,False,80.6576,0.0,0,Clear sky
2,2015-08-14,2015,8,14,17,30,40,Friday,False,False,False,False,80.6576,0.0,0,Clear sky
3,2015-08-14,2015,8,14,17,40,44,Friday,False,False,False,False,80.6576,0.0,0,Clear sky
4,2015-08-14,2015,8,14,17,50,45,Friday,False,False,False,False,80.6576,0.0,0,Clear sky
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62075,2017-03-17,2017,3,17,23,20,7,Friday,False,False,False,True,54.2300,0.0,3,Overcast
62076,2017-03-17,2017,3,17,23,30,5,Friday,False,False,False,True,54.2300,0.0,3,Overcast
62077,2017-03-17,2017,3,17,23,40,2,Friday,False,False,False,True,54.2300,0.0,3,Overcast
62078,2017-03-17,2017,3,17,23,50,0,Friday,False,False,False,True,54.2300,0.0,3,Overcast
62079,2017-03-17,2017,3,17,23,0,0,Friday,False,False,False,True,54.2300,0.0,3,Overcast

In [4]:
# Export as a csv for further use
df.to_csv("../data/processed/clean_gym_data.csv", index=False)

### Analysis

In [5]:
clear_weather = df[df["rain_mm"] == 0]
clear_weather_avg = clear_weather.groupby("day_of_week")["number_people"].mean()

rainy_weather = df[df["rain_mm"] > 0]
rainy_weather_avg = rainy_weather.groupby("day_of_week")["number_people"].mean()

merged_df_2 = pd.merge(clear_weather_avg, rainy_weather_avg, on="day_of_week").reset_index()
merged_df_2.rename(columns={"number_people_x":"clear_avg","number_people_y":"rainy_avg"}, inplace=True)
merged_df_2["rain_penalty"] = merged_df_2["rainy_avg"] - merged_df_2["clear_avg"]
rain_penalty = merged_df_2

rain_penalty = rain_penalty[["day_of_week","rain_penalty"]]
rain_penalty

  day_of_week  rain_penalty
0      Friday      3.937187
1      Monday     -9.977016
2    Saturday      1.645923
3      Sunday      2.034177
4    Thursday      1.737461
5     Tuesday    -12.127372
6   Wednesday     -2.294729

In [6]:
is_holiday = df
is_holiday = is_holiday.groupby("is_holiday")["number_people"].mean().reset_index()

no_holiday_avg = is_holiday[is_holiday["is_holiday"] == False]["number_people"].values[0]
holiday_avg = is_holiday[is_holiday["is_holiday"] == True]["number_people"].values[0]

holiday_penalty = holiday_avg - no_holiday_avg

In [ ]:
base = clear_weather
base = base.groupby(["day_of_week","hour"])["number_people"].mean().reset_index()
# base

keys = list(zip(base["day_of_week"], base["hour"]))
values = base["number_people"]
reference_base = dict(zip(keys,values))
# reference_base

{('Friday', 0): 21.308108108108108,
 ('Friday', 1): 3.6869565217391305,
 ('Friday', 2): 0.1836734693877551,
 ('Friday', 3): 0.21875,
 ('Friday', 4): 0.34806629834254144,
 ('Friday', 5): 1.3453947368421053,
 ('Friday', 6): 10.819718309859155,
 ('Friday', 7): 19.124293785310734,
 ('Friday', 8): 26.6566757493188,
 ('Friday', 9): 31.746630727762803,
 ('Friday', 10): 34.93766937669377,
 ('Friday', 11): 36.696883852691215,
 ('Friday', 12): 38.91812865497076,
 ('Friday', 13): 36.96470588235294,
 ('Friday', 14): 37.78285714285714,
 ('Friday', 15): 41.94767441860465,
 ('Friday', 16): 48.07848837209303,
 ('Friday', 17): 54.46511627906977,
 ('Friday', 18): 50.388739946380696,
 ('Friday', 19): 44.632876712328766,
 ('Friday', 20): 38.083109919571044,
 ('Friday', 21): 36.524324324324326,
 ('Friday', 22): 33.56318681318681,
 ('Friday', 23): 6.392953929539296,
 ('Monday', 0): 16.944881889763778,
 ('Monday', 1): 2.5701754385964914,
 ('Monday', 2): 0.17592592592592593,
 ('Monday', 3): 0.09302325581395349,
 ('Monday', 4): 0.21164021164021163,
 ('Monday', 5): 0.9674267100977199,
 ('Monday', 6): 12.194915254237289,
 ('Monday', 7): 20.12146892655367,
 ('Monday', 8): 27.5414364640884,
 ('Monday', 9): 32.270270270270274,
 ('Monday', 10): 34.595238095238095,
 ('Monday', 11): 37.724795640326974,
 ('Monday', 12): 39.18032786885246,
 ('Monday', 13): 38.50268817204301,
 ('Monday', 14): 37.0377358490566,
 ('Monday', 15): 39.75067024128686,
 ('Monday', 16): 46.4559585492228,
 ('Monday', 17): 53.83116883116883,
 ('Monday', 18): 54.590673575129536,
 ('Monday', 19): 51.526041666666664,
 ('Monday', 20): 48.840425531914896,
 ('Monday', 21): 52.064516129032256,
 ('Monday', 22): 48.47027027027027,
 ('Monday', 23): 38.1484375,
 ('Saturday', 0): 0.72264631043257,
 ('Saturday', 1): 0.3346774193548387,
 ('Saturday', 2): 0.24074074074074073,
 ('Saturday', 3): 0.09767441860465116,
 ('Saturday', 4): 0.13170731707317074,
 ('Saturday', 5): 0.5944272445820433,
 ('Saturday', 6): 0.6016949152542372,
 ('Saturday', 7): 2.205797101449275,
 ('Saturday', 8): 15.84070796460177,
 ('Saturday', 9): 27.04437869822485,
 ('Saturday', 10): 33.52818991097923,
 ('Saturday', 11): 36.5207100591716,
 ('Saturday', 12): 34.620289855072464,
 ('Saturday', 13): 33.73295454545455,
 ('Saturday', 14): 34.33913043478261,
 ('Saturday', 15): 35.04733727810651,
 ('Saturday', 16): 37.84659090909091,
 ('Saturday', 17): 39.97808219178082,
 ('Saturday', 18): 39.10182767624021,
 ('Saturday', 19): 35.16710875331565,
 ('Saturday', 20): 32.377049180327866,
 ('Saturday', 21): 34.532967032967036,
 ('Saturday', 22): 32.82093663911846,
 ('Saturday', 23): 5.553191489361702,
 ('Sunday', 0): 0.5279187817258884,
 ('Sunday', 1): 0.22265625,
 ('Sunday', 2): 0.14215686274509803,
 ('Sunday', 3): 0.12254901960784313,
 ('Sunday', 4): 0.20725388601036268,
 ('Sunday', 5): 0.2,
 ('Sunday', 6): 0.2898550724637681,
 ('Sunday', 7): 1.0458452722063036,
 ('Sunday', 8): 12.853025936599424,
 ('Sunday', 9): 23.896656534954406,
 ('Sunday', 10): 27.858895705521473,
 ('Sunday', 11): 31.520833333333332,
 ('Sunday', 12): 30.24251497005988,
 ('Sunday', 13): 28.090379008746357,
 ('Sunday', 14): 27.578034682080926,
 ('Sunday', 15): 29.818181818181817,
 ('Sunday', 16): 32.089635854341736,
 ('Sunday', 17): 38.28,
 ('Sunday', 18): 38.00544959128065,
 ('Sunday', 19): 37.65040650406504,
 ('Sunday', 20): 36.5521978021978,
 ('Sunday', 21): 37.73684210526316,
 ('Sunday', 22): 37.09668508287293,
 ('Sunday', 23): 27.994490358126722,
 ('Thursday', 0): 21.851318944844124,
 ('Thursday', 1): 3.682170542635659,
 ('Thursday', 2): 0.12669683257918551,
 ('Thursday', 3): 0.16019417475728157,
 ('Thursday', 4): 0.30392156862745096,
 ('Thursday', 5): 1.4126074498567336,
 ('Thursday', 6): 11.29023746701847,
 ('Thursday', 7): 19.965699208443272,
 ('Thursday', 8): 27.101333333333333,
 ('Thursday', 9): 30.834688346883468,
 ('Thursday', 10): 34.49030470914128,
 ('Thursday', 11): 35.59065934065934,
 ('Thursday', 12): 34.94602272727273,
 ('Thursday', 13): 33.44477611940299,
 ('Thursday', 14): 32.712609970674485,
 ('Thursday', 15): 35.93732193732194,
 ('Thursday', 16): 43.86612021857923,
 ('Thursday', 17): 49.20754716981132,
 ('Thursday', 18): 49.27704485488127,
 ('Thursday', 19): 44.675392670157066,
 ('Thursday', 20): 42.19178082191781,
 ('Thursday', 21): 44.247887323943665,
 ('Thursday', 22): 44.18181818181818,
 ('Thursday', 23): 35.409470752089135,
 ('Tuesday', 0): 22.016867469879518,
 ('Tuesday', 1): 3.5142857142857142,
 ('Tuesday', 2): 0.24285714285714285,
 ('Tuesday', 3): 0.2175925925925926,
 ('Tuesday', 4): 0.40703517587939697,
 ('Tuesday', 5): 1.3685800604229608,
 ('Tuesday', 6): 12.872340425531915,
 ('Tuesday', 7): 22.535064935064934,
 ('Tuesday', 8): 29.08564231738035,
 ('Tuesday', 9): 32.87979539641944,
 ('Tuesday', 10): 36.14921465968586,
 ('Tuesday', 11): 38.297814207650276,
 ('Tuesday', 12): 36.787234042553195,
 ('Tuesday', 13): 35.92225201072386,
 ('Tuesday', 14): 34.556164383561644,
 ('Tuesday', 15): 38.6968085106383,
 ('Tuesday', 16): 47.0,
 ('Tuesday', 17): 45.49591836734694,
 ('Tuesday', 18): 55.25369458128079,
 ('Tuesday', 19): 51.60493827160494,
 ('Tuesday', 20): 48.8525,
 ('Tuesday', 21): 50.11616161616162,
 ('Tuesday', 22): 46.91361256544503,
 ('Tuesday', 23): 36.653543307086615,
 ('Wednesday', 0): 20.029850746268657,
 ('Wednesday', 1): 2.9915254237288136,
 ('Wednesday', 2): 0.16267942583732056,
 ('Wednesday', 3): 0.1291866028708134,
 ('Wednesday', 4): 0.38144329896907214,
 ('Wednesday', 5): 1.5345911949685536,
 ('Wednesday', 6): 13.488250652741515,
 ('Wednesday', 7): 22.56122448979592,
 ('Wednesday', 8): 28.914438502673796,
 ('Wednesday', 9): 33.425257731958766,
 ('Wednesday', 10): 35.37150127226463,
 ('Wednesday', 11): 37.795918367346935,
 ('Wednesday', 12): 38.57800511508952,
 ('Wednesday', 13): 35.62820512820513,
 ('Wednesday', 14): 34.450127877237854,
 ('Wednesday', 15): 38.43126684636118,
 ('Wednesday', 16): 46.592,
 ('Wednesday', 17): 54.10079575596817,
 ('Wednesday', 18): 51.792307692307695,
 ('Wednesday', 19): 48.42857142857143,
 ('Wednesday', 20): 47.386842105263156,
 ('Wednesday', 21): 48.557291666666664,
 ('Wednesday', 22): 44.294429708222815,
 ('Wednesday', 23): 35.79493670886076}

In [8]:
def is_raining(rain_mm):
    if rain_mm > 0:
        return True
    else:
        return False

def get_weather_forecast(target_date):
    cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
    retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
    openmeteo = openmeteo_requests.Client(session = retry_session)

    # Make sure all required weather variables are listed here
    # The order of variables in hourly or daily is important to assign them correctly below
    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        "latitude": 37.8716,
        "longitude": -122.2728,
        "hourly": ["temperature_2m", "rain", "precipitation_probability"],
        "temperature_unit": "fahrenheit",
        "timezone": "America/Los_Angeles",
        "start_date": target_date,
        "end_date": target_date
    }
    responses = openmeteo.weather_api(url, params=params)

    # Process first location. Add a for-loop for multiple locations or weather models
    response = responses[0]
    """
    print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
    print(f"Elevation: {response.Elevation()} m asl")
    print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")
    """
    
    # Process hourly data. The order of variables needs to be the same as requested.
    hourly = response.Hourly()
    hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
    hourly_rain = hourly.Variables(1).ValuesAsNumpy()
    hourly_precipitation_probability = hourly.Variables(2).ValuesAsNumpy()

    hourly_data = {"date": pd.date_range(
        start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
        end =  pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
        freq = pd.Timedelta(seconds = hourly.Interval()),
        inclusive = "left"
    )}

    hourly_data["temperature_2m"] = hourly_temperature_2m
    hourly_data["rain"] = hourly_rain
    hourly_data["precipitation_probability"] = hourly_precipitation_probability

    hourly_dataframe = pd.DataFrame(data = hourly_data)
    hourly_dataframe['date'] = hourly_dataframe['date'].dt.tz_convert('America/Los_Angeles')

    hourly_dataframe.rename(columns={'rain': 'rain_mm'}, inplace=True)
    hourly_dataframe["hour"] = hourly_dataframe["date"].dt.hour
    hourly_dataframe["is_raining"] = hourly_dataframe["rain_mm"].apply(is_raining)

    hourly_dataframe.drop(columns=['date','temperature_2m'], inplace=True)

    return hourly_dataframe

In [17]:
def predict_gym_traffic(target_date, target_hour):
    # Get if it will rain
    forecast = get_weather_forecast(target_date)
    is_raining = forecast[forecast["hour"] == target_hour]["is_raining"].values[0]

    # Get if date is a holiday
    if target_date in ca_holidays:
        is_holiday = True
    else:
        is_holiday = False

    # Get day of the week
    target_date = pd.to_datetime(target_date)
    day = target_date.day_name()
    key = (day, target_hour)

    rainpenalty = rain_penalty[rain_penalty["day_of_week"] == day]["rain_penalty"].values[0]
    forecast_base = reference_base.get(key, 0)

    forecast_final = forecast_base

    if is_raining:
        forecast_final += rainpenalty
    if is_holiday:
        forecast_final += holiday_penalty
    
    return max(0, round(forecast_final))

# predict_gym_traffic('2026-02-05',17)